// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FactorialServiceClient is the client API for FactorialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FactorialServiceClient interface {
	Factorial(ctx context.Context, in *FactorialRequest, opts ...grpc.CallOption) (*FactorialResponse, error)
}

type factorialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFactorialServiceClient(cc grpc.ClientConnInterface) FactorialServiceClient {
	return &factorialServiceClient{cc}
}

func (c *factorialServiceClient) Factorial(ctx context.Context, in *FactorialRequest, opts ...grpc.CallOption) (*FactorialResponse, error) {
	out := new(FactorialResponse)
	err := c.cc.Invoke(ctx, "/factorialService/Factorial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactorialServiceServer is the server API for FactorialService service.
// All implementations must embed UnimplementedFactorialServiceServer
// for forward compatibility
type FactorialServiceServer interface {
	Factorial(context.Context, *FactorialRequest) (*FactorialResponse, error)
	mustEmbedUnimplementedFactorialServiceServer()
}

// UnimplementedFactorialServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFactorialServiceServer struct {
}

func (UnimplementedFactorialServiceServer) Factorial(context.Context, *FactorialRequest) (*FactorialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Factorial not implemented")
}
func (UnimplementedFactorialServiceServer) mustEmbedUnimplementedFactorialServiceServer() {}

// UnsafeFactorialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FactorialServiceServer will
// result in compilation errors.
type UnsafeFactorialServiceServer interface {
	mustEmbedUnimplementedFactorialServiceServer()
}

func RegisterFactorialServiceServer(s grpc.ServiceRegistrar, srv FactorialServiceServer) {
	s.RegisterService(&FactorialService_ServiceDesc, srv)
}

func _FactorialService_Factorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactorialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactorialServiceServer).Factorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/factorialService/Factorial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactorialServiceServer).Factorial(ctx, req.(*FactorialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FactorialService_ServiceDesc is the grpc.ServiceDesc for FactorialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FactorialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "factorialService",
	HandlerType: (*FactorialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Factorial",
			Handler:    _FactorialService_Factorial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/protob.proto",
}
